TITLE: Ricardo Campos Blog
TITLE_HTML: Ricardo Campos
TAGLINE: Welcome to my personal page
POSTS_PER_PAGE: 10
AUTHOR: Ricardo Campos
DISQUS: ricardocamposblog-1
TIMEZONE: UTC
#POST_EXT: .rst
LOCALE: en